# Используем официальный образ Python
FROM python:3.9-slim

# Устанавливаем дополнительные зависимости из requirements.txt
#COPY ./app/requirements.txt /app/requirements.txt
#RUN pip install --no-cache-dir -r /app/requirements.txt


# Устанавливаем зависимости
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Устанавливаем FastAPI и Uvicorn
RUN pip install --no-cache-dir fastapi uvicorn

# Устанавливаем PyTorch
RUN pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
RUN pip install matplotlib


# Копируем файлы приложения в контейнер
COPY ./app /app


# Устанавливаем рабочую директорию
WORKDIR /app

# Указываем команду для запуска приложения
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
