# Используем официальный образ Python
FROM python:3.9-slim

# Устанавливаем зависимости
RUN pip install --no-cache-dir flask requests pillow

# Копируем файлы приложения в контейнер
COPY ./flask_app /app

# Устанавливаем рабочую директорию
WORKDIR /app

# Указываем команду для запуска приложения
CMD ["python", "main.py"]
